import { Box, Flex } from "@chakra-ui/react";
import Navbar from "@/components/navbar";
import Head from "next/head";
import Header from "@/components/header";

export default function Layout({ children, metaTitle, metaDescription }) {
    return (
        <>
        <Head>
            <title>NextJs - {metaTitle}</title>
            <meta name="description" content={metaDescription || "Generated by create next app"} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Flex direction="column" minH="100vh" align="center" bg="gray.50">
            {/* Konten Utama */}
            <Header title={metaTitle} />
            <Box
                flex="1"
                width="100%"
                maxWidth="480px" // Maksimal lebar 480px
                mx="auto"         // Center horizontal
                p={4}             // Padding untuk spasi dalam konten
                bg="white"        // Latar belakang putih untuk konten
                boxShadow="sm"    // Tambahkan shadow untuk estetika
                borderRadius="md" // Membuat sudut konten melengkung
            >
                {children}
            </Box>

            {/* Bottom Navbar */}
            <Navbar />
        </Flex>
        </>
    );
}
